#!/usr/bin/python

from __future__ import print_function

import sys
import time
import random

args = sys.argv[1:]

delay = float(args[0]) if len(args) else 2.0

columns = "abcdefgh"
rows    = map(str, range(1, 9))

while True:
    col_index = random.randint(0, 7)
    row_index = random.randint(0, 7)
    color     = "white" if (col_index + row_index) % 2 else "black"
    print(columns[col_index] + rows[row_index], end="... ")
    sys.stdout.flush()
    time.sleep(delay)
    print(color)

